### ISSUE TITLE
Easier buffer navigation

### ISSUE THREAD

**Issue by thiru** [Musab-Nazir/vim-config#1]
I see you're using vim-airline.  I used to use it but changed to lightline instead for some unknown reason.

But it looks like it's pretty easy to add a buffer-line to airline (tabs across the top) with this setting:

`let g:airline#extensions#tabline#enabled = 1`

I then use the following binding to navigate the buffers:

```
nnoremap <C-j> :bp<CR>
nnoremap <C-k> :bn<CR>
```

**Comment by Musab-Nazir** [comment]
This was exactly what I needed. Thanks a lot! 😄
